### ISSUE TITLE
你好，插件在IDEA2016.3.5上有些问题，请问还继续更新吗？

### ISSUE THREAD

**Issue by linxingwu** [myoss/profile#20]
复制压缩com文件夹之后，idea里以已经可以使用。但是每次idea启动时，都会报IDEA FATAL ERRORS.具体错误信息是NoClassDefFoundError:com/ref/idea/common/data/BasicData.
`com/ref/idea/common/data/BasicData
java.lang.NoClassDefFoundError: com/ref/idea/common/data/BasicData
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
	at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:276)
	at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:272)
	at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:241)
	at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:125)
	at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:74)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:63)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.seventh7.mybatis.ref.CmProject$2.run(CmProject.java:70)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.ref.idea.common.data.BasicData PluginClassLoader[com.seventh7.plugin.mybatis, 2.91]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:65)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 12 `

**Comment by myoss** [comment]
你把这个文件删除掉了吧？ ref.idea.common-1.0.jar
